linters:
  fast: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck

#    - bodyclose
#    - golint
#    - rowserrcheck
#    - stylecheck
#    - gosec
#    - interfacer
#    - unconvert
#    - dupl
#    - goconst
#    - gocyclo
#    - gocognit
#    - asciicheck
#    - gofmt
#    - goimports
#    - maligned
#    - depguard
#    - misspell
#    - lll
#    - unparam
#    - dogsled
#    - nakedret
#    - prealloc
#    - scopelint
#    - gocritic
#    - gochecknoinits
#    - gochecknoglobals
#    - godox
#    - funlen
#    - whitespace
#    - wsl
#    - goprintffuncname
#    - gomnd
#    - goerr113
#    - gomodguard
#    - godot
#    - testpackage
#    - nestif
#    - nolintlint
#    - megacheck

#    - https://github.com/kyoh86/exportloopref
#    - https://github.com/kyoh86/looppointer
